spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/assessment-ibcs-primax?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
